In [1]:
import pandas as pd

In [7]:
# g = pd.read_json("data/politicians_with_gender.json")

In [8]:
gender = pd.read_pickle("data/politicians_with_gender")

In [6]:
# g.head()

In [10]:
views = pd.read_json("model/politicians_pw.json")

In [9]:
gender.head()

,#DBpURL,ID,WikiURL,birthDate,deathDate,first_name,fpp_gender,full_name,gender,genderize,name,nationality,occupation,party
0,http://dbpedia.org/resource/Quincy_Timberlake,11,http://en.wikipedia.org/wiki/Quincy_Timberlake,1980-04-22 00:00:00,None,quincy,NaN,Quincy+Timberlake,male,NaN,"[ quincy timberlake , timberlake quincy ]",[kenyan],[politician],[]
1,http://dbpedia.org/resource/Fanny_Edelman,29,http://en.wikipedia.org/wiki/Fanny_Edelman,1911-02-27 00:00:00,2011-11-01 00:00:00,fanny,NaN,Fanny+Edelman,female,NaN,"[ fanny edelman , edelman fanny ]",[argentine],[politician],[]
3,http://dbpedia.org/resource/Paul_Scheffer,102,http://en.wikipedia.org/wiki/Paul_Scheffer,1954-09-03 00:00:00,None,paul,NaN,Paul+Scheffer,male,NaN,[ scheffer paul ],[],[politician],[]
4,http://dbpedia.org/resource/Ed_Robb,127,http://en.wikipedia.org/wiki/Ed_Robb,None,None,ed,NaN,Ed+Robb,male,NaN,[],[american],[politician],[]
5,http://dbpedia.org/resource/Nizamettin_Erkmen,144,http://en.wikipedia.org/wiki/Nizamettin_Erkmen,None,1990-10-24 00:00:00,nizamettin,NaN,Nizamettin+Erkmen,male,NaN,[ erkmen nizamettin ],[turkish],[politician],[]

In [42]:
s_views = views[['ID','views']]
dec = s_views = views[['ID','dec2016']]
s_views.head()
# gender['dec2016'] = views.dec2016

          ID  dec2016
0         11      262
1         29      564
10    166654      334
100   168066      147
1000  181770     2264

In [41]:
step = pd.merge(gender, s_views, left_on = "ID", right_on = "ID")

In [44]:
all_stuff_fn = pd.merge(step, dec,left_on = "ID", right_on = "ID")

In [46]:
all_stuff_fn.to_pickle("data/politicians_gend_views")

In [48]:
all_stuff_fn.head()

,#DBpURL,ID,WikiURL,birthDate,deathDate,first_name,fpp_gender,full_name,gender,genderize,name,nationality,occupation,party,views,dec2016
0,http://dbpedia.org/resource/Quincy_Timberlake,11,http://en.wikipedia.org/wiki/Quincy_Timberlake,1980-04-22 00:00:00,None,quincy,NaN,Quincy+Timberlake,male,NaN,"[ quincy timberlake , timberlake quincy ]",[kenyan],[politician],[],5106,262
1,http://dbpedia.org/resource/Fanny_Edelman,29,http://en.wikipedia.org/wiki/Fanny_Edelman,1911-02-27 00:00:00,2011-11-01 00:00:00,fanny,NaN,Fanny+Edelman,female,NaN,"[ fanny edelman , edelman fanny ]",[argentine],[politician],[],5228,564
2,http://dbpedia.org/resource/Paul_Scheffer,102,http://en.wikipedia.org/wiki/Paul_Scheffer,1954-09-03 00:00:00,None,paul,NaN,Paul+Scheffer,male,NaN,[ scheffer paul ],[],[politician],[],4518,370
3,http://dbpedia.org/resource/Ed_Robb,127,http://en.wikipedia.org/wiki/Ed_Robb,None,None,ed,NaN,Ed+Robb,male,NaN,[],[american],[politician],[],1170,90
4,http://dbpedia.org/resource/Nizamettin_Erkmen,144,http://en.wikipedia.org/wiki/Nizamettin_Erkmen,None,1990-10-24 00:00:00,nizamettin,NaN,Nizamettin+Erkmen,male,NaN,[ erkmen nizamettin ],[turkish],[politician],[],916,183